apiVersion: v1alpha
kind: xctest
sauce:
  concurrency: 1
xctest:
  app: ./build/ios_integ/Build/Products/Runner.ipa
  xcTestRunFile: ./build/ios_integ/Build/Products/Runner_iphoneos18.2-arm64.xctestrun
suites:
  - name: "Basic XCTest"
    devices:
      - name: ".*"
artifacts:
  download:
    when: always
    match:
      - "*.*"
    directory: ./